# Generated by Django 3.2.5 on 2024-05-27 02:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeUsu', models.CharField(default=None, max_length=255, null=True)),
                ('telefoneUsu', models.CharField(default=None, max_length=14, null=True, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('imagemPerfil', models.BinaryField(default=None, null=True)),
                ('statusAtivo', models.BooleanField(default=False)),
                ('dataCriacao', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('avaliacaoId', models.AutoField(primary_key=True, serialize=False)),
                ('qtdEstrelas', models.PositiveSmallIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('dataAvaliacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCategoria', models.CharField(max_length=255)),
                ('imagem', models.BinaryField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodVerif',
            fields=[
                ('CodVerifId', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', fernet_fields.fields.EncryptedTextField(max_length=6, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('statusAtivo', models.BooleanField(default=True)),
                ('duracao_expiracao_minutos', models.PositiveIntegerField(default=5)),
                ('data_hora_expiracao', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('contaBancariaId', models.AutoField(primary_key=True, serialize=False)),
                ('digitAgencia', fernet_fields.fields.EncryptedTextField(max_length=2)),
                ('numConta', fernet_fields.fields.EncryptedTextField()),
                ('nomeBanco', fernet_fields.fields.EncryptedTextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('cupomId', models.AutoField(primary_key=True, serialize=False)),
                ('valorDesconto', models.FloatField()),
                ('dataValidade', models.DateField()),
                ('limiteUso', models.SmallIntegerField()),
                ('valorMinimo', models.FloatField()),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('enderecoId', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(default=None, max_length=255, null=True)),
                ('cidade', models.CharField(default=None, max_length=255, null=True)),
                ('estado', models.CharField(default=None, max_length=2, null=True)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(default=None, max_length=255, null=True)),
                ('pontoReferencia', models.CharField(default=None, max_length=255, null=True)),
                ('coordenadas', models.CharField(default=None, max_length=20, null=True)),
                ('apelido', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('estabelecimentoId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeEstab', models.CharField(max_length=255)),
                ('telefoneEstab', models.CharField(max_length=14)),
                ('imagemEstab', models.BinaryField(default=None, null=True)),
                ('imagemBanner', models.BinaryField(default=None, null=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('emailEstab', models.CharField(max_length=255)),
                ('avaliacaoId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.avaliacao')),
                ('categoriaId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.categoria')),
                ('enderecoId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaPedido',
            fields=[
                ('etapaPedidoId', models.AutoField(primary_key=True, serialize=False)),
                ('etapaPedido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPag',
            fields=[
                ('formaPagId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeFormaPag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegraCupom',
            fields=[
                ('regraCupomId', models.AutoField(primary_key=True, serialize=False)),
                ('descricaoRegra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('tipoAvaliacaoId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipoUsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTipoUsuario', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('tipoVeiculoId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produtoId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProd', models.CharField(max_length=255)),
                ('disponibilidade', models.BooleanField()),
                ('preco', models.FloatField()),
                ('imagemProd', models.BinaryField(default=None, null=True)),
                ('alcoolico', models.BooleanField()),
                ('descricao', models.TextField()),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.categoria')),
                ('estabelecimentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedidoId', models.AutoField(primary_key=True, serialize=False)),
                ('statusAtivo', models.BooleanField(default=True)),
                ('dataPedido', models.DateField(default=datetime.datetime(2024, 5, 26, 23, 51, 33, 858878))),
                ('gorjeta', models.SmallIntegerField(null=True)),
                ('cupomld', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.cupom')),
                ('etapaPedidoId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.etapapedido')),
                ('formaPagld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.formapag')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('notificacaoId', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('dataRecebimento', models.DateField()),
                ('cupomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.cupom')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('itemPedidoId', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.CharField(default=None, max_length=255, null=True)),
                ('qtdItens', models.SmallIntegerField(default=1)),
                ('pedidoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.pedido')),
                ('produtoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('favoritosId', models.AutoField(primary_key=True, serialize=False)),
                ('estabelecimentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.estabelecimento')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregadorVeic',
            fields=[
                ('tipoVeiculoId', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=8)),
                ('cnh', models.CharField(max_length=11)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoEntrega',
            fields=[
                ('enderecoEntregaId', models.AutoField(primary_key=True, serialize=False)),
                ('enderecoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.endereco')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuponsUsuario',
            fields=[
                ('cuponsUsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('cupomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.cupom')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cupom',
            name='regraCupomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.regracupom'),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('cartaoId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeBandeira', models.CharField(max_length=255)),
                ('numCartao', fernet_fields.fields.EncryptedTextField(max_length=16)),
                ('validade', fernet_fields.fields.EncryptedTextField()),
                ('cvv', fernet_fields.fields.EncryptedTextField(max_length=3)),
                ('nomeTitular', fernet_fields.fields.EncryptedTextField(max_length=255)),
                ('cpfCnpj', fernet_fields.fields.EncryptedTextField(max_length=14)),
                ('apelidoCartao', models.CharField(max_length=255)),
                ('formaPagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.formapag')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipoAvaliacaoId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.tipoavaliacao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codVerifId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.codverif'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contaBancariaId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.contabancaria'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuarioId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.tipousuario'),
        ),
    ]
