# Generated by Django 3.2.5 on 2024-03-19 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codverif',
            name='dataEnvio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
