# Generated by Django 3.2.5 on 2024-05-12 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='cartaold',
            new_name='cartaoId',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 11, 46, 33, 471908)),
        ),
    ]
