# Generated by Django 3.2.5 on 2024-04-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
