# Generated by Django 3.2.5 on 2024-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='imagemEstab',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
