# Generated by Django 3.2.5 on 2024-04-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuarioId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.tipousuario'),
        ),
    ]
