# Generated by Django 3.2.5 on 2024-04-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='estabelecimentold',
            new_name='estabelecimentoId',
        ),
    ]
