# Generated by Django 3.2.5 on 2024-05-30 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_alter_pedido_datapedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cupomld',
            new_name='cupomId',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='formaPagld',
            new_name='formaPagId',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 15, 20, 36, 835313)),
        ),
    ]
