# Generated by Django 3.2.5 on 2024-03-06 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_auto_20240305_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataCriacao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
