# Generated by Django 3.2.5 on 2024-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_categoria_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codverif',
            old_name='dataEnvio',
            new_name='dataCriacao',
        ),
        migrations.AddField(
            model_name='codverif',
            name='statusAtivo',
            field=models.BooleanField(default=False),
        ),
    ]
