# Generated by Django 3.2.5 on 2024-05-12 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_auto_20240512_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapaPedido',
            fields=[
                ('etapaPedidoId', models.AutoField(primary_key=True, serialize=False)),
                ('etapaPedido', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 12, 25, 29, 974290)),
        ),
        migrations.AddField(
            model_name='pedido',
            name='etapaPedidold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.etapapedido'),
        ),
    ]
