# Generated by Django 3.2.5 on 2024-03-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_alter_codverif_dataenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='coordenadas',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codVerifId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.codverif'),
        ),
    ]
