# Generated by Django 3.2.5 on 2024-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_auto_20240408_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codverif',
            name='codigo',
            field=models.CharField(default='448886', max_length=6),
        ),
    ]
