# Generated by Django 3.2.5 on 2024-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0002_alter_usuario_tipousuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='statusAtivo',
            field=models.BooleanField(default=False),
        ),
    ]
