# Generated by Django 3.2.5 on 2024-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0003_auto_20240408_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codverif',
            name='statusAtivo',
            field=models.BooleanField(default=True),
        ),
    ]
