# Generated by Django 3.2.5 on 2024-05-12 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0003_auto_20240512_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 12, 46, 47, 887240)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='formaPagld',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.formapag'),
            preserve_default=False,
        ),
    ]
