# Generated by Django 3.2.5 on 2024-03-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0003_auto_20240306_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
