# Generated by Django 3.2.5 on 2024-04-30 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0003_alter_usuario_statusativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='statusPedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='statusAtivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 20, 2, 24, 652591)),
        ),
    ]
