# Generated by Django 3.2.5 on 2024-04-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0003_alter_estabelecimento_imagemestab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='imagemEstab',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
