# Generated by Django 3.2.5 on 2024-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0004_alter_codverif_statusativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codverif',
            name='codigo',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
