# Generated by Django 3.2.5 on 2024-03-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0004_alter_usuario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagemPerfil',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeUsu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefoneUsu',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
