# Generated by Django 3.2.5 on 2024-05-01 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0004_auto_20240430_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='observacao',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cupomld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.cupom'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 21, 21, 14, 830909)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='formaPagld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.formapag'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='gorjeta',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='statusAtivo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorTotal',
            field=models.FloatField(null=True),
        ),
    ]
