# Generated by Django 3.2.5 on 2024-03-07 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0005_auto_20240307_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='enderecoId',
        ),
        migrations.CreateModel(
            name='LocalEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderecoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.endereco')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
