# Generated by Django 3.2.5 on 2024-05-12 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0005_auto_20240512_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapag',
            old_name='formaPag',
            new_name='formaPagId',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 13, 38, 43, 991925)),
        ),
    ]
