# Generated by Django 3.2.5 on 2024-05-06 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0006_auto_20240501_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuariold',
            new_name='usuarioId',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 23, 25, 16, 552297)),
        ),
    ]
