# Generated by Django 3.2.5 on 2024-05-12 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0006_auto_20240512_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 13, 58, 52, 753039)),
        ),
    ]
