# Generated by Django 3.2.5 on 2024-03-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0007_rename_ativo_usuario_statusativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
