# Generated by Django 3.2.5 on 2024-05-12 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0007_alter_pedido_datapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='imagemBanner',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 14, 41, 15, 921837)),
        ),
    ]
