# Generated by Django 3.2.5 on 2024-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0008_auto_20240307_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contaBancariaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.contabancaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuarioId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.tipousuario'),
        ),
    ]
