# Generated by Django 3.2.5 on 2024-05-12 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0009_alter_pedido_datapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 44, 24, 408224)),
        ),
    ]
