# Generated by Django 3.2.5 on 2024-05-22 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0012_auto_20240512_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='produtold',
            new_name='produtoId',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cupomld',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifoodApp.cupom'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 0, 2, 22, 672664)),
        ),
    ]
